##Python Tutorial: Using Try/Except Blocks for Error Handling
try:
    f = open('test_file.txt')
except FileNotFoundError as e:
    print(e)
except Exception as e:
    print(e)
else:
    print(f.read())
    f.close()
finally:
    print('Excuting finally...')

